# Generated by Django 2.2.4 on 2019-09-05 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_item', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('date_lent', models.DateTimeField(auto_now_add=True)),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('initial_item_for_borrow', models.CharField(max_length=255)),
                ('shed_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Item')),
            ],
        ),
    ]
