# Generated by Django 2.2.4 on 2019-09-05 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='initial_item_for_borrow',
        ),
    ]
