# Generated by Django 2.2.4 on 2019-09-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='initial_item_price',
            field=models.CharField(default='cup of tea', max_length=255),
            preserve_default=False,
        ),
    ]
