# Generated by Django 2.2.4 on 2019-09-14 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
