# Generated by Django 2.2.4 on 2019-10-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20191004_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='messages',
        ),
    ]
