# Generated by Django 2.2.4 on 2019-10-04 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_profile_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user_who_borrowed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_borrowed', to='community.Profile'),
        ),
    ]
