# Generated by Django 2.2.4 on 2019-10-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20191003_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='message',
            new_name='messages',
        ),
    ]
