# Generated by Django 2.2.4 on 2019-09-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20190905_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shed_items',
        ),
        migrations.AddField(
            model_name='profile',
            name='shed_items',
            field=models.ManyToManyField(to='community.Item'),
        ),
    ]
