# Generated by Django 2.2.4 on 2019-09-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20190905_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='initial_item',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
