# Generated by Django 2.2.4 on 2019-09-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20190907_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
