# Generated by Django 2.2.4 on 2019-09-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_remove_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileName',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
