# Generated by Django 2.2.4 on 2019-09-08 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_profile_profilename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileName',
            new_name='profile_name',
        ),
    ]
