# Generated by Django 2.2.4 on 2019-09-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
